name: 'Release: Create GitHub Release'
run-name: 'Create GitHub Release by @${{ github.actor }} on ${{ github.event_name }}'

on:
  push:
    tags:
      - 'v*' # Chỉ kích hoạt khi có tag dạng v*

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12'
          registry-url: 'https://registry.npmjs.org/'

      # 3. Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, eslint, typescript]

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # 5. Run Lint + Prepublish build
      - name: Build and Lint
        run: pnpm run prepublishOnly

      # 6. Build package
      - name: Build
        run: pnpm run build

      # 7. Tạo CHANGELOG.md từ commit history
      - name: Generate CHANGELOG.md
        run: |
          echo "🎉 Tự động tạo release cho tag ${{ github.ref_name }}" > changelog.md
          echo "" >> changelog.md
          echo "## ${GITHUB_REF_NAME}" > changelog.md
          echo "" >> changelog.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> changelog.md

      # 8. Đóng gói release files
      - name: Package release files
        run: |
          mkdir release
          cp -r dist release/
          cp README.md LICENSE changelog.md release/
          cd release && zip -r ../n8n-nodes-nqdev-${{ github.ref_name }}.zip .

      # 9. Create GitHub Release with asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: changelog.md
          files: |
            n8n-nodes-nqdev-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}

      # 10. Cleanup
      - name: Cleanup
        run: |
          rm -rf release
          rm changelog.md
          rm -rf dist
          rm -rf node_modules
          pnpm store prune
          pnpm cache clean --all
